@extends('peserta::layouts.student')

@section('title', 'Jelajahi Kursus - Balai Kursus')

@section('content')
<div class="min-h-screen bg-[#f7f8f6] px-4 py-8 sm:px-6 lg:px-10">
    <div class="mx-auto max-w-7xl">
        <header class="mb-8 flex flex-col gap-5 border-b border-[#dce7e5] pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p class="font-mono text-xs uppercase tracking-[0.22em] text-[#0d9488]">Ruang peserta / katalog</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-[#173f5f]">Jelajahi kursus</h1><p class="mt-3 text-[#718596]">Temukan kelas yang sesuai dengan program, level, dan kebutuhan belajar Anda.</p></div><a href="{{ route('peserta.pendaftaran.index') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#c8d9d6] bg-white px-4 py-3 text-sm font-semibold text-[#40627d] transition hover:border-[#0d9488] hover:text-[#0f766e]"><i class="bi bi-clipboard-check"></i>Pendaftaran saya</a></header>
        @if($errors->any())<div class="mb-6 border-l-4 border-[#dc2626] bg-[#fef2f2] px-5 py-4 text-sm text-[#991b1b]"><p class="font-semibold">Ada yang perlu diperiksa.</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $err)<li>{{ $err }}</li>@endforeach</ul></div>@endif
        @if(session('success'))<div class="mb-6 border-l-4 border-[#16a34a] bg-[#f0fdf4] px-5 py-4 text-sm text-[#166534]">{{ session('success') }}</div>@endif
        @if(session('error'))<div class="mb-6 border-l-4 border-[#d97706] bg-[#fffaf0] px-5 py-4 text-sm text-[#92400e]">{{ session('error') }}</div>@endif

        <div class="mb-8"><label for="filterInputPesertaKursus" class="sr-only">Cari kursus</label><div class="relative max-w-2xl"><i class="bi bi-search absolute left-4 top-1/2 -translate-y-1/2 text-[#0d9488]"></i><input type="search" id="filterInputPesertaKursus" placeholder="Cari kursus, program, level, atau instruktur..." class="w-full rounded-xl border border-[#c8d9d6] bg-white py-3.5 pl-11 pr-4 text-[#173f5f] placeholder-[#8da0ad] shadow-sm outline-none transition focus:border-[#0d9488] focus:ring-4 focus:ring-[#0d9488]/10"></div></div>

        @if($kursus->isEmpty())<div class="border border-dashed border-[#b8cbc8] bg-white px-6 py-16 text-center"><i class="bi bi-inbox text-4xl text-[#0d9488]"></i><h2 class="mt-4 text-2xl font-bold text-[#173f5f]">Belum ada kursus</h2><p class="mt-2 text-[#718596]">Silakan cek kembali nanti.</p></div>@else
            <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@foreach($kursus as $index => $k)<article class="peserta-kursus-item group flex flex-col border border-[#dce7e5] bg-white p-5 shadow-[0_14px_35px_rgba(23,63,95,.06)] transition duration-200 hover:-translate-y-0.5 hover:border-[#0d9488] hover:shadow-[0_18px_42px_rgba(23,63,95,.12)]"><div class="flex items-start justify-between gap-3"><span class="font-mono text-sm text-[#d97706]">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</span><span class="rounded-full bg-[#e8f7f4] px-3 py-1 font-mono text-[10px] font-semibold uppercase text-[#0f766e]">{{ $k->status }}</span></div><h2 class="mt-5 line-clamp-2 text-xl font-bold leading-tight text-[#173f5f]">{{ $k->nama }}</h2><div class="mt-4 space-y-2 text-sm text-[#718596]"><p><i class="bi bi-diagram-3 mr-2 text-[#0d9488]"></i>{{ $k->program->nama }}</p><p><i class="bi bi-bar-chart mr-2 text-[#0d9488]"></i>{{ $k->level->nama }}</p><p><i class="bi bi-person-badge mr-2 text-[#0d9488]"></i>{{ $k->instruktur->nama_instr }}</p></div><div class="mt-6 border-t border-[#e8efed] pt-4"><p class="font-mono text-[11px] uppercase tracking-[0.16em] text-[#718596]">Investasi belajar</p><p class="mt-1 text-2xl font-bold text-[#173f5f]">Rp {{ number_format($k->harga,0,',','.') }}</p>@if($k->harga_upi)<p class="mt-1 text-xs text-[#718596]">Harga UPI: Rp {{ number_format($k->harga_upi,0,',','.') }}</p>@endif</div><div class="mt-6 grid grid-cols-2 gap-2"><a href="/peserta/kursus/{{ $k->id }}" class="inline-flex min-h-10 items-center justify-center rounded-lg border border-[#c8d9d6] px-3 py-2 text-sm font-semibold text-[#40627d] transition hover:border-[#0d9488] hover:bg-[#e8f7f4] hover:text-[#0f766e]"><i class="bi bi-eye mr-2"></i>Detail</a><form action="{{ route('peserta.kursus.daftar',$k->id) }}" method="POST">@csrf<button type="submit" class="inline-flex min-h-10 w-full items-center justify-center rounded-lg bg-[#0d9488] px-3 py-2 text-sm font-semibold text-white transition hover:bg-[#0f766e]"><i class="bi bi-check2 mr-2"></i>Daftar</button></form></div></article>@endforeach</div>
        @endif
    </div>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('filterInputPesertaKursus');if(!input)return;input.addEventListener('input',()=>{const q=input.value.toLowerCase();document.querySelectorAll('.peserta-kursus-item').forEach(item=>{item.hidden=!item.innerText.toLowerCase().includes(q);});});});</script>
@endsection
